version: '3'

services:
  db:
    image: oracle/database:18.3.0-ee
    environment:
      - ORACLE_PWD=<password>
      - ORACLE_SID=<sid>
      - ORACLE_PDB=<pdb_name>
      - ORACLE_CHARACTERSET=<character_set>
    ports:
      - "1521:1521"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
