# Generated by Django 4.1.4 on 2022-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMail', models.CharField(max_length=50)),
                ('userCountryCode', models.CharField(max_length=2)),
                ('userPresenterId', models.IntegerField()),
                ('userStatus', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=3)),
                ('surname', models.CharField(max_length=30)),
                ('phonePrefix', models.CharField(max_length=7)),
                ('userLanguage', models.CharField(max_length=2)),
                ('phoneNumber', models.DecimalField(decimal_places=2, max_digits=20)),
                ('acceptTermsCondition', models.CharField(max_length=1)),
                ('acceptPrivacy', models.CharField(max_length=1)),
                ('acceptStatistics', models.CharField(max_length=1)),
                ('promoCode', models.CharField(max_length=10)),
            ],
        ),
    ]
