# Generated by Django 4.1.4 on 2022-12-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProg', models.IntegerField()),
                ('appID', models.IntegerField()),
                ('userStatus', models.IntegerField()),
            ],
        ),
    ]
