# Generated by Django 4.1.4 on 2022-12-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_userprog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='userID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
