# Generated by Django 4.1.4 on 2022-12-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verUserProg', models.IntegerField()),
                ('verCodeType', models.CharField(max_length=1)),
                ('verStartDate', models.DateTimeField()),
                ('lastLoginerr', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
                ('cterr', models.IntegerField()),
                ('lasttentative', models.DateTimeField()),
            ],
        ),
    ]
