# Generated by Django 4.1.4 on 2022-12-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_verificationcodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodemodel',
            name='verificationCode',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
