# Generated by Django 4.1.4 on 2022-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_verificationcodemodel_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodemodel',
            name='verEndDate',
            field=models.DateTimeField(default='2021-01-01 00:00:00'),
        ),
    ]
