# Generated by Django 4.1.4 on 2023-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_app_companymodel_customer_expert_passwordmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='functionType',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
