# Generated by Django 4.1.4 on 2023-01-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customermodel_expertmodel_delete_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userType',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
