# Generated by Django 4.1.4 on 2023-01-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_languagemodel_uploadimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='userPresenterId',
            new_name='userPresenterID',
        ),
    ]
