# Generated by Django 4.1.4 on 2023-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_userpresenterid_usermodel_userpresenterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='cus_mail',
            field=models.CharField(max_length=50),
        ),
    ]
