# Generated by Django 4.1.4 on 2023-01-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_customermodel_cus_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='cus_address1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_companyauthlevel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_companyrole',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_docid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_docimgackid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_docimgfrontid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_doctype',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_postcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_residenceproofimg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='cus_vatcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
