# Generated by Django 4.1.4 on 2023-01-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_customermodel_cus_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='comp_address1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrepdocid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrepdocimgackid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrepdocimgfrontid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrepdoctype',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrepmail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrepname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrepsurname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_legalrpcountry',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_postcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_sectorid',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_vatcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
