# Generated by Django 4.1.4 on 2023-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_companymodel_comp_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='comp_mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_prog',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
