# Generated by Django 4.1.4 on 2023-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_companymodel_comp_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userProg',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
