# Generated by Django 4.1.4 on 2023-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_usermodel_id_alter_usermodel_userprog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userProg',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
