# Generated by Django 4.1.4 on 2023-01-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_usermodel_userprog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AlterModelTable(
            name='app',
            table='app',
        ),
        migrations.AlterModelTable(
            name='companymodel',
            table='company',
        ),
        migrations.AlterModelTable(
            name='countrymodel',
            table='country',
        ),
        migrations.AlterModelTable(
            name='customermodel',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='expertmodel',
            table='expert',
        ),
        migrations.AlterModelTable(
            name='languagemodel',
            table='language',
        ),
        migrations.AlterModelTable(
            name='passwordmodel',
            table='password',
        ),
        migrations.AlterModelTable(
            name='planapp',
            table='plan_app',
        ),
        migrations.AlterModelTable(
            name='plandetails',
            table='plan_details',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='promocode',
            table='promo_code',
        ),
        migrations.AlterModelTable(
            name='userapp',
            table='user_app',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userpaymet',
            table='user_pay_met',
        ),
        migrations.AlterModelTable(
            name='verificationcodemodel',
            table='verification_code',
        ),
    ]
