# Generated by Django 4.1.4 on 2023-01-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_delete_uploadimage_alter_app_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcodemodel',
            old_name='cterr',
            new_name='vercterr',
        ),
        migrations.RenameField(
            model_name='verificationcodemodel',
            old_name='lastLoginerr',
            new_name='verlastLoginerr',
        ),
        migrations.RenameField(
            model_name='verificationcodemodel',
            old_name='lasttentative',
            new_name='verlasttentative',
        ),
        migrations.RenameField(
            model_name='verificationcodemodel',
            old_name='status',
            new_name='verstatus',
        ),
    ]
