# Generated by Django 4.1.4 on 2023-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_cterr_verificationcodemodel_vercterr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='comp_address1',
            new_name='comp_address',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='cus_address1',
            new_name='cus_address',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='cus_city',
            new_name='cus_nationalid',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='comp_address2',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='comp_city',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='comp_legalrepdocid',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='comp_legalrepdoctype',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='comp_postcode',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='cus_address2',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='cus_docid',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='cus_doctype',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='cus_postcode',
        ),
        migrations.AddField(
            model_name='companymodel',
            name='comp_legalrepdocendvalidity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='cus_docendvalidity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_mail2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_maildelegat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_phonenumber2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='comp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
