# Generated by Django 4.1.4 on 2023-01-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_rename_comp_address1_companymodel_comp_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='comp_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
