# Generated by Django 4.1.4 on 2023-01-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_companymodel_comp_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
