# Generated by Django 4.1.4 on 2023-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_usermodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userPresenterID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
