# Generated by Django 4.1.4 on 2023-01-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_usermodel_userpresenterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='userName',
        ),
    ]
