# Generated by Django 4.1.4 on 2023-01-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_usermodel_name_remove_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='surname',
        ),
    ]
