# Generated by Django 4.1.4 on 2023-01-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_qrcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userProg',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
