# Generated by Django 4.1.4 on 2023-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_usermodel_userprog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_userprogr', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_status', models.CharField(choices=[('list of value', 'list of value')], max_length=20)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=20)),
                ('phone_endverification', models.DateTimeField(blank=True, null=True)),
                ('phone_endvalidity', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
