# Generated by Django 4.1.4 on 2023-01-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_rename_acceptprivacy_usermodel_user_acceptprivacy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userCountryCode',
            new_name='user_CountryCode',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userID',
            new_name='user_ID',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userLanguage',
            new_name='user_Language',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userMail',
            new_name='user_Mail',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userPresenterID',
            new_name='user_PresenterID',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userProg',
            new_name='user_Prog',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userStatus',
            new_name='user_Status',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_userType',
            new_name='user_Type',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_user_mail2',
            new_name='user_mail2',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_user_maildelegat',
            new_name='user_maildelegat',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_user_phonenumber2',
            new_name='user_phonenumber2',
        ),
    ]
