# Generated by Django 4.1.4 on 2023-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_rename_user_usercountrycode_usermodel_user_countrycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_globalfinancialid',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_ID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_Mail',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
