# Generated by Django 4.1.4 on 2023-01-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_usermodel_user_globalfinancialid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_globalfinancialid',
        ),
    ]
